2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 551, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 773, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1160, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1343, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1744, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1915, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1609, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3147, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2246, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2310, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2434, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2704, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2164, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3407, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3519, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3214, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3616, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3806, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3946, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4202, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4314, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4328, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4342, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4366, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4380, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4354, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4527, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4394, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4406, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4418, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4430, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4466, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4539, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4551, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4563, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4577, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4591, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4605, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 602, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 714, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1096, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4630, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1389, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1794, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4662, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4646, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4710, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4678, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4694, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2508, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3100, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4726, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3682, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 519, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 502, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 486, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4742, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3860, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4758, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4775, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:14
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4262, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 551, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 773, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1160, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1343, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1744, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1915, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1609, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3147, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2246, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2310, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2434, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2704, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2164, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3407, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3519, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3214, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3616, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3806, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3946, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4202, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4314, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4328, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4342, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4366, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4380, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4354, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4527, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4394, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4406, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4418, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4430, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4466, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4539, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4551, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4563, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4577, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4591, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4605, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 602, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 714, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1096, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4630, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1389, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1794, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4662, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4646, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4710, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4678, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4694, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2508, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3100, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4726, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3682, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 519, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 502, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 486, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4742, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3860, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4758, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4775, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2014-11-13 17:52:16
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3065/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 458, in is_visible_
    ret = self.is_visible()
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4262, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 10:33:04
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/neumann/Library/Application Support/Sublime Text 3/Packages/SVN/SVN.py", line 402, in run_with_except
    SVN.init(svn_binary_path=settings_dict['svn_binary_path'])
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 840, in init
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 876, in get_version
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



2015-09-18 13:33:43
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/neumann/Library/Application Support/Sublime Text 3/Packages/SVN/SVN.py", line 402, in run_with_except
    SVN.init(svn_binary_path=settings_dict['svn_binary_path'])
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 840, in init
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 876, in get_version
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 173, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4262, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2490, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4202, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3806, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1915, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1160, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:05:58
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 191, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:21
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 173, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:22
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4262, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:22
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2490, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:22
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4202, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:22
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3806, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:22
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1915, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:22
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1160, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:20:22
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 191, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 173, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4262, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2490, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4202, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3806, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1915, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1160, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:24:36
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 191, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 173, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4262, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 2490, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 4202, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 3806, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1915, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 1160, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-18 18:29:05
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 456, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 191, in is_visible
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/commands.py", line 116, in has_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 62, in get_wc_root
SVN.sublimesvn.errors.PluginLoadingError: SVN still loading
2015-09-23 12:52:17
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/neumann/Library/Application Support/Sublime Text 3/Packages/SVN/SVN.py", line 402, in run_with_except
    SVN.init(svn_binary_path=settings_dict['svn_binary_path'])
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 840, in init
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 876, in get_version
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



2015-09-28 18:41:54
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/neumann/Library/Application Support/Sublime Text 3/Packages/SVN/SVN.py", line 402, in run_with_except
    SVN.init(svn_binary_path=settings_dict['svn_binary_path'])
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 840, in init
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 876, in get_version
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



2015-09-28 18:44:42
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/neumann/Library/Application Support/Sublime Text 3/Packages/SVN/SVN.py", line 402, in run_with_except
    SVN.init(svn_binary_path=settings_dict['svn_binary_path'])
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 840, in init
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 876, in get_version
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



2015-09-29 10:21:40
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/neumann/Library/Application Support/Sublime Text 3/Packages/SVN/SVN.py", line 402, in run_with_except
    SVN.init(svn_binary_path=settings_dict['svn_binary_path'])
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 840, in init
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 876, in get_version
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError: 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



